name: ci
on:
  push:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.3

      - name: Format
        run: terraform fmt -check

  plan:
    needs: format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCLOUD_AUTH }}"

      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.3

      - name: Init
        run: |
          cd terraform
          terraform init

      - name: Plan
        run: |
          export TF_VAR_project_id=$GCP_PROJECT_ID
          export TF_VAR_region=$GCP_REGION
          export TF_VAR_service_name=$GCP_SERVICE_NAME
          export TF_VAR_image_name=$GCP_IMAGE_NAME
          cd terraform
          terraform plan
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_REGION: ${{ secrets.GCP_REGION }}
          GCP_SERVICE_NAME: ${{ secrets.GCP_SERVICE_NAME }}
          GCP_IMAGE_NAME: ${{ secrets.GCP_IMAGE_NAME }}
